// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARW0FLjCxFV2jY_uIaTcnkdkorZ1eyB_4',
    appId: '1:587680693093:web:03620c4949610f5ca6ff8c',
    messagingSenderId: '587680693093',
    projectId: 'weflytest-b601c',
    authDomain: 'weflytest-b601c.firebaseapp.com',
    storageBucket: 'weflytest-b601c.appspot.com',
    measurementId: 'G-1S4YQN4NN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4aTpgW3tb6lpSBZy1VrXVfFBM9LAlb8A',
    appId: '1:587680693093:android:1778b996c6aa6046a6ff8c',
    messagingSenderId: '587680693093',
    projectId: 'weflytest-b601c',
    storageBucket: 'weflytest-b601c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGWOp8XHvs9RlUTgZJjdSaUnMx3hNS4FM',
    appId: '1:587680693093:ios:ac1f4cc4799c8b4ba6ff8c',
    messagingSenderId: '587680693093',
    projectId: 'weflytest-b601c',
    storageBucket: 'weflytest-b601c.appspot.com',
    iosClientId: '587680693093-d845rieqqjvp20d3a7kmjb13sl4g1lmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.weflyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGWOp8XHvs9RlUTgZJjdSaUnMx3hNS4FM',
    appId: '1:587680693093:ios:ac1f4cc4799c8b4ba6ff8c',
    messagingSenderId: '587680693093',
    projectId: 'weflytest-b601c',
    storageBucket: 'weflytest-b601c.appspot.com',
    iosClientId: '587680693093-d845rieqqjvp20d3a7kmjb13sl4g1lmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.weflyProject',
  );
}
